export enum Manufacturer {
    NOMA_SHIPPING_GROUP = 'NOMA_SHIPPING_GROUP',
    JUPITER_INDUSTRIES = 'JUPITER_INDUSTRIES',
    ANTONIOS_CONSORTIUM = 'ANTONIOS_CONSORTIUM',
    DAWN_ACCORD = 'DAWN_ACCORD',
    HAYREDDIN_CLAN = 'HAYREDDIN_CLAN',
    THUNDERBOLT_GROUP = 'THUNDERBOLT_GROUP',
}

/*
ARES_CORPS,
DEFENDER_FORCE,
EAGLE_GUARD,
GERMANICUS_CORPS,
PANGU,
STAR_LIBERTADORES,
THUNDERBOLT_GROUP
*/
