export enum ResearchManufacturer {
    NOMA_SHIPPING_GROUP = 'RESEARCH_NOMA_SHIPPING_GROUP',
    JUPITER_INDUSTRIES = 'RESEARCH_JUPITER_INDUSTRIES',
    ANTONIOS_CONSORTIUM = 'RESEARCH_ANTONIOS_CONSORTIUM',
    DAWN_ACCORD = 'RESEARCH_DAWN_ACCORD',
}
