export enum ResearchStrategyType {
    OUTSTANDING_FIREPOWER = 'OUTSTANDING_FIREPOWER',
    SUSTAINED_COMBAT = 'SUSTAINED_COMBAT',
    STRATEGY_AND_SUPPORT = 'STRATEGY_AND_SUPPORT',
    FIGHTER_AND_CORVETTE = 'FIGHTER_AND_CORVETTE',
}
